// Generated by youlin-contracts/scripts/export-abi.ts. Do not edit manually.
export const youlinDeployment = {
  deployed: true,
  chainId: 10143,
  network: "Monad Testnet",
  explorerUrl: "https://testnet.monadscan.com",
  protocol: "0x60634746d377ea1d71F78cB22bf8436D34e15B99",
  legacyProtocol: "0x20a1Df8893fD7531A77E225f9727b45959D2ff66",
  legacyProjectCount: 8,
  firstOpenProjectId: 9,
  reputation: "0x3f3C0f177C4076aCb9be40198d9Ff93a74D5a3c3",
  participation: "0xa8B7b596b9ebcA4Eb8BF6d9f95Ef68DcEB758CeF",
  genesisTreasury: "0xe4a470a21E272945fcDAAF7625f6D11703183fC6",
  genesisDeployed: true,
  profileRegistry: "0x3d6Bd044f11018114c1793E80Aed53d230D46Ac7",
  profileDeployed: true,
} as const;
