// Generated by youlin-contracts/scripts/export-abi.ts. Do not edit manually.
export const youlinDeployment = {
  deployed: false,
  chainId: 10143,
  network: "Monad Testnet",
  explorerUrl: "https://testnet.monadscan.com",
  protocol: "0x0000000000000000000000000000000000000000",
  reputation: "0x0000000000000000000000000000000000000000",
  participation: "0x0000000000000000000000000000000000000000",
} as const;
