import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type Deployment = {
  chainId: number;
  network: string;
  explorerUrl: string;
  contracts: {
    YoulinProtocol: string;
    YoulinReputation: string;
    YoulinParticipation: string;
    YoulinGenesisTreasury?: string;
  };
};

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const contractsRoot = path.resolve(scriptDirectory, "..");
const frontendContractsDirectory = path.resolve(
  contractsRoot,
  "..",
  "..",
  "youlin-interface",
  "lib",
  "contracts",
);
const contractNames = [
  "YoulinProtocol",
  "YoulinReputation",
  "YoulinParticipation",
  "YoulinGenesisTreasury",
] as const;

await mkdir(frontendContractsDirectory, { recursive: true });

for (const contractName of contractNames) {
  const artifactPath = path.join(
    contractsRoot,
    "artifacts",
    "contracts",
    `${contractName}.sol`,
    `${contractName}.json`,
  );
  const artifact = JSON.parse(await readFile(artifactPath, "utf8")) as {
    abi: unknown[];
  };
  await writeFile(
    path.join(frontendContractsDirectory, `${contractName}.abi.json`),
    `${JSON.stringify(artifact.abi, null, 2)}\n`,
    "utf8",
  );
}

let deployment: Deployment | undefined;
try {
  deployment = JSON.parse(
    await readFile(
      path.join(contractsRoot, "deployments", "monad-testnet.json"),
      "utf8",
    ),
  ) as Deployment;
} catch (error) {
  const code = (error as NodeJS.ErrnoException).code;
  if (code !== "ENOENT") throw error;
}

const zeroAddress = "0x0000000000000000000000000000000000000000";
const addresses = deployment?.contracts ?? {
  YoulinProtocol: zeroAddress,
  YoulinReputation: zeroAddress,
  YoulinParticipation: zeroAddress,
};
const output = `// Generated by youlin-contracts/scripts/export-abi.ts. Do not edit manually.
export const youlinDeployment = {
  deployed: ${deployment !== undefined},
  chainId: ${deployment?.chainId ?? 10143},
  network: ${JSON.stringify(deployment?.network ?? "Monad Testnet")},
  explorerUrl: ${JSON.stringify(
    deployment?.explorerUrl ?? "https://testnet.monadscan.com",
  )},
  protocol: ${JSON.stringify(addresses.YoulinProtocol)},
  reputation: ${JSON.stringify(addresses.YoulinReputation)},
  participation: ${JSON.stringify(addresses.YoulinParticipation)},
  genesisTreasury: ${JSON.stringify(
    addresses.YoulinGenesisTreasury ?? zeroAddress,
  )},
  genesisDeployed: ${Boolean(addresses.YoulinGenesisTreasury)},
} as const;
`;
await writeFile(
  path.join(frontendContractsDirectory, "addresses.ts"),
  output,
  "utf8",
);

console.log(
  `Exported ${contractNames.length} ABIs and addresses to ${frontendContractsDirectory}`,
);
